### ISSUE TITLE
como eu faço para abaixar o comcraft mod loader sever

### ISSUE THREAD

**Issue by figuifreedos** [simon816/ComcraftModLoader#19]
ola eu gostaria de saber onde posso abaixar o comcraft mod loader sever porque eu quero muito jogar com o meu primo será que alguém pode me ajudar

**Comment by simon816** [comment]
Hi,
you can find the server download here: https://www.simon816.com/project/comcraftml/downloads/
> Comcraft Mod Loader Server (PC ONLY)

Source code available here: https://github.com/simon816/ComcraftServer

**Comment by figuifreedos** [comment]
thanks

Em qui, 24 de mar de 2022 10:53 PM, Simon816 ***@***.***>
escreveu:

**Comment by figuifreedos** [comment]
thanks ; )
